---
- name: Analysis
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true

  vars:
    rhsm_username: pwatt@deploypartners.com
    rhsm_password: Fred1234$
    rhsm_org: MY_ORG
    rhsm_activation_key: MY_ACTIVATION_KEY

  tasks:
    - name: Generate pre-conversion analysis report
      ansible.builtin.import_role:
        name: infra.convert2rhel.analysis
...
