- name: Update CentOS-Base.repo
  hosts: all
  become: yes
  tasks:
    - name: Get current CentOS release
      command: cat /etc/centos-release
      register: centos_release

    - name: Display CentOS release version
      debug:
        msg: "Current CentOS release: {{ centos_release.stdout }}"
        
    - name: Modify CentOS-Base.repo
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^#baseurl=http://mirror.centos.org/centos/(.*)$'
        replace: 'baseurl=http://vault.centos.org/centos/\1'
      register: repo_modified

    - name: Comment out mirrorlist entries
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
      when: repo_modified.changed

    - name: Clean yum cache
      command: yum clean all
      when: repo_modified.changed

    - name: Update yum cache
      command: yum makecache
      when: repo_modified.changed

    - name: Update CentOS to the latest version
      yum:
        name: '*'
        state: latest
      when: repo_modified.changed

    - name: Reboot the machine
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      when: repo_modified.changed

    - name: Wait for the system to come back online
      wait_for_connection:
        delay: 10
        timeout: 300
      when: repo_modified.changed
      
    - name: Get current CentOS release
      command: cat /etc/centos-release
      register: centos_release

    - name: Display CentOS release version
      debug:
        msg: "Current CentOS release: {{ centos_release.stdout }}"
