- name: Update CentOS-Base.repo
  hosts: all
  become: yes
  tasks:
    - name: Modify CentOS-Base.repo
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^#baseurl=http://mirror.centos.org/centos/(.*)$'
        replace: 'baseurl=http://vault.centos.org/centos/\1'
      register: repo_modified

    - name: Comment out mirrorlist entries
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
      when: repo_modified.changed

    - name: Clean yum cache
      command: yum clean all
      when: repo_modified.changed

    - name: Update yum cache
      command: yum makecache
      when: repo_modified.changed

    - name: Update CentOS to the latest version
      yum:
        name: '*'
        state: latest
      when: repo_modified.changed

    - name: Reboot the system
      reboot:
        msg: "Reboot initiated by Ansible after updating CentOS."
        reboot_timeout: 300
      when: repo_modified.changed

    - name: Wait for the system to become reachable
      wait_for_connection:
        timeout: 300
      when: repo_modified.changed
